Don't really see how the inventory can be null in an inventory click event...
java.lang.NullPointerException: null at me.eccentric_nz.TARDIS.listeners.TARDISAccessoryListener.onHelmetSlotEquip(TARDISAccessoryListener.java:26)